### ISSUE TITLE
custom menu

### ISSUE THREAD

**Issue by orleanski** [pseudorook/capsule#15]
Thank you for creation of hugo theme with  bulma framework.

Would you please shed some light how to organize top navigation menu  in custom order?
Right now it is in alphabetical order, I think, and let's say About_Us should be a the end, but pushed to the first position in the menu.

Thank you in advance.

**Comment by sudorook** [comment]
I've found two ways to get the "About" button to the right. (Examples below assume TOML format.)

## Option 1: Edit the site config file

Edit the site config file and add the lines:
```
[menu]
  [[menu.main]]
  identifier = "bleep"
  name = "Bleep"
  url = "/bleep/"
  weight = 10
  [[menu.main]]
  identifier = "bloop"
  name = "Bloop"
  url = "/bloop/"
  weight = 20
.
.
.
```

This is to be done for _all_ the subdirectories, where the value of each variable corresponds to the directory name. Adjust the weights to get the menu items in the order you want. Weights are sorted in ascending (left-to-right) order.

## Option 2

Alternatively, add the metadata inside the content subdirectories themselves.

For subdirectories containing collections of posts, add a file called `_index.md` (or whatever extension). To each `_index.md` file, add the header:
```
+++
title = "Foo"
weight = 10
+++
```

For subdirectories that correspond to a single page instead of a page with a list of posts (e.g. an "About" page), just edit the `index.md` header rather than create an `_index.md` file. Append to the header/frontmatter:
```
+++
[menu.main]
  name = "Foo"
  identifier = "foo"
  weight = 10
+++
```

## Note on weights

It's not possible to only set the weight for the "About" page. _All_ the pages have to be weighted because the Hugo site menu generator sorts pages in a bizarre manner:

```
[...non-zero weighted sections...][...0-weighted and unweighted sections...]
```

Any non-zero weights (including negative ones!) show up on the left. 0-weighted or unweighted on the right. Because equal weights are then sorted alphabetically, a page called "About" will never end up all the way on the right unless you happen to have other menu sections that alphabetically sort before

## Note on new layout

Incidentally, I haven't yet added a custom layout for "About" pages, so for now I added a new layout (simple.html) that's blank except for header, footer, title, and meta tags. You can use `layout = "simple"` if the default adds too much to the page.
